FROM python:3.12.0-slim-bookworm 

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -yq \
        wget \
        git \
        openssh-server \
        unzip \
        tar \
        build-essential


# Install conda 
RUN wget -q -P /tmp \
  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -u /opt/conda \
    && rm /tmp/Miniconda3-latest-Linux-x86_64.sh
ENV PATH="/opt/conda/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/lib:$LD_LIBRARY_PATH"
RUN conda update --all -y && \
    conda update conda -y && \
    conda update -n base -c conda-forge conda

## Install mamba from conda-forge
RUN conda install -y -c conda-forge \
    mamba

## Install mamba packages
RUN mamba install -y -c conda-forge \
    openbabel \
    rdkit 

# Install python requirements
COPY ./requirements.txt /app/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
    -r /app/requirements.txt

# SSH setup
RUN mkdir /var/run/sshd \
    && echo 'root:password' | chpasswd \
    && sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start SSH daemon
WORKDIR /app
CMD ["/usr/sbin/sshd", "-D"]